app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('', include('django_prometheus.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

app/core/urls.py
from django.urls import path
from . import views


app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),    
]

app/core/models.py
from django.db import models

class Sample(models.Model):
    attachment = models.FileField()

app/core/views.py
import time, random
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.contrib.auth.models import User
# from prometheus_client import Summary, Histogram


# s = Summary('summary_latency_seconds', 'Dashboard response latency in seconds')
# h = Histogram('histogram_latency_seconds', 'Dashboard response latency in seconds')


def index(request):
    return render(request, 'core/index.html')


def register(request):
  if request.method == 'POST':
    # Get form values
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']
    username = request.POST['username']
    email = request.POST['email']
    password = request.POST['password']
    password2 = request.POST['password2']

    # Check if passwords match
    if password == password2:
      # Check username
      if User.objects.filter(username=username).exists():
        messages.error(request, 'That username is taken')
        return redirect('core:register')
      else:
        if User.objects.filter(email=email).exists():
          messages.error(request, 'That email is being used')
          return redirect('core:register')
        else:
          # Looks good
          user = User.objects.create_user(username=username, password=password,email=email, first_name=first_name, last_name=last_name)
          user.save()
          messages.success(request, 'You are now registered and can log in')
          return redirect('core:login')
    else:
      messages.error(request, 'Passwords do not match')
      return redirect('core:register')
  else:
    return render(request, 'core/register.html')


def login(request):
  ## Add random delay ##
  # time.sleep(random.randint(1, 10))
  if request.method == 'POST':
    username = request.POST['username']
    password = request.POST['password']

    user = auth.authenticate(username=username, password=password)

    if user is not None:
      auth.login(request, user)
      ## start_time ##
      request.session['start_time'] = time.time()
      return redirect('core:dashboard')
    else:
      messages.error(request, 'Invalid credentials')
      return redirect('core:login')
  else:
    return render(request, 'core/login.html')


def logout(request):
  if request.method == 'POST':
    auth.logout(request)
    return redirect('core:index')


def dashboard(request):
    ## Add delay ##
    # time.sleep(3)
    ## total_time ##
    total_time = time.time() - request.session.get('start_time')
    ## Instrument ##
    # s.observe(total_time)
    # h.observe(total_time)
    return render(request, 'core/dashboard.html')

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard App</title>
    <!--Bootstrap-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    {% include 'partials/_navbar.html' %}    
    {% block content %} {% endblock %}
    {% include 'partials/_footer.html' %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.esm.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

app/templates/core/dashboard.html
{% extends 'base.html' %}
{% block content %}
<section id="showcase-inner" class="py-5">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h1 class="display-4">User Dashboard</h1>
                <p class="lead">Window to your Game On! world</p>
            </div>
        </div>
    </div>
</section>
<section id="dashboard" class="py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>Welcome, {{ user.first_name }}!</h2>

            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/core/index.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
<section id="showcase">
    <div class="container text-center">
        <img src="{% static 'img/keyboard-gaming.jpg' %}" width="900px" height="600px">
    </div>
</section>
{% endblock %}

app/templates/core/login.html
{% extends 'base.html' %}

{% block content %}
<section id="login" class="bg-light py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        <h4>
                            <i class="fas fa-sign-in-alt"></i> Login
                        </h4>
                    </div>
                    <div class="card-body">
                        <!-- Messages -->
                        {% include 'partials/_messages.html' %}
                        <form action="{% url 'core:login' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group mb-3">
                                <label for="username">Username</label>
                                <input type="text" name="username" class="form-control" required>
                            </div>
                            <div class="form-group mb-3">
                                <label for="password2">Password</label>
                                <input type="password" name="password" class="form-control" required>
                            </div>
                            <div class="text-center">
                                <input type="submit" value="Login" class="btn btn-primary btn-block">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/core/register.html
{% extends 'base.html' %}

{% block content %}
<section id="register" class="bg-light py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        <h4>Register</h4>
                    </div>
                    <div class="card-body">
                        <!-- Messages -->
                        {% include 'partials/_messages.html' %}                        
                        <form action="{% url 'core:register' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group mb-3">
                                <label for="first_name">First Name</label>
                                <input type="text" name="first_name" class="form-control" required>
                            </div>
                            <div class="form-group mb-3">
                                <label for="last_name">Last Name</label>
                                <input type="text" name="last_name" class="form-control" required>
                            </div>
                            <div class="form-group mb-3">
                                <label for="username">Username</label>
                                <input type="text" name="username" class="form-control" required>
                            </div>
                            <div class="form-group mb-3">
                                <label for="email">Email</label>
                                <input type="email" name="email" class="form-control" required>
                            </div>
                            <div class="form-group mb-3">
                                <label for="password2">Password</label>
                                <input type="password" name="password" class="form-control" required>
                            </div>
                            <div class="form-group mb-3">
                                <label for="password">Confirm Password</label>
                                <input type="password" name="password2" class="form-control" required>
                            </div>
                            <div class="text-center">
                                <input type="submit" value="Register" class="btn btn-primary btn-block">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/partials/_footer.html
<!-- Footer -->
<footer id="main-footer" class="py-4 bg-secondary text-white text-center">
    Copyright &copy;
    <span class="year"></span> Game On!
</footer>

app/templates/partials/_messages.html
{% if messages %}
{% for message in messages %}
<div id="message" class="container">
    <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
        <strong>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Error:
            {% else %}
            {{ message.tags|title }}
            {% endif %}
        </strong>
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> 
        </button>
    </div>
</div>
{% endfor %}
{% endif %}

app/templates/partials/_navbar.html
{% load static %}
<!--Navbar-->
<nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top">
    <div class="container">
        <a href="{% url 'core:index' %}" class="navbar-brand">
            <p class="display-4">
            Game On!
            </p>
        </a>
        <button 
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navmenu"
        >
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navmenu">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'core:dashboard' %}"
                            {% if 'dashboard' in request.path %}
                                class="nav-link active" 
                            {% else %}
                                class="nav-link" 
                            {% endif %}
                            >
                            Welcome {{ user.username }} (Dashboard)
                        </a>    
                    </li>
                    <li class="nav-item">
                        <a href="javascript:{document.getElementById('logout').submit()}" class="nav-link">
                            Logout
                        </a>
                        <form action="{% url 'core:logout' %}" method="POST" id="logout">
                            {% csrf_token %}
                            <input type="hidden">
                        </form>                         
                    </li>                    
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'core:register' %}"
                            {% if 'register' in request.path %}
                                class="nav-link active" 
                            {% else %}
                                class="nav-link" 
                            {% endif %}
                            >
                            Register
                        </a>    
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'core:login' %}"
                            {% if 'Login' in request.path %}
                                class="nav-link active" 
                            {% else %}
                                class="nav-link" 
                            {% endif %}
                            >
                            Login
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>    
    </div>
</nav>